/**
 * MERN Tenant Management System - Verification & Trust Platform Feature Flags
 * Governs Demo vs Production behavior and feature toggles across UI components.
 */

export const FEATURE_FLAGS = {
  DEMO_MODE: true,
  VERIFICATION: true,
  REAL_IDENTITY_VERIFICATION: false,
  REAL_PROPERTY_VERIFICATION: false,
  REAL_DIGILOCKER_VERIFICATION: false,
  REAL_FACIAL_VERIFICATION: false,
  REAL_VIDEO_KYC_VERIFICATION: false,
  TRUST_SCORE: true,
  PROPERTY_VERIFICATION: true,
  TECHNICIAN_VERIFICATION: true,
  MANAGER_VERIFICATION: true,
  TENANT_VERIFICATION: true,
  FACE_VERIFICATION: false,
  DIGILOCKER: false,
  AADHAAR: false,
  PAN: false,
  BUSINESS_VERIFICATION: false,
  VIDEO_KYC: false,
  BACKGROUND_CHECK: false,
  EMPLOYMENT_VERIFICATION: false,
  LAND_REGISTRY: false,
  PROPERTY_TAX: false,
  GEO_VERIFICATION: false,
  SAFETY_CERTIFICATE: false,
  UTILITY_VERIFICATION: false,
  NSDC_VERIFICATION: false,
  POLICE_VERIFICATION: false,
  INSURANCE_VERIFICATION: false,
  SKILL_CERTIFICATION: false,
  AUTO_REVIEW: true,
  MULTI_LEVEL_REVIEW: true,
  SLA_TRACKING: true,
  ADMIN_VERIFICATION_CENTER: true,
  OCR_VERIFICATION: false,
  AI_DOCUMENT_VALIDATION: false,
  BACKGROUND_SCREENING: false,
  FRAUD_ENGINE: false,
  AUTO_ASSIGN_REVIEWER: false,
  AUTO_APPROVAL: false,
  ADVANCED_ANALYTICS: true,
};

export default FEATURE_FLAGS;
