/**
 * Standardized dot-notated Domain Event Categories.
 */
export const EventTypes = {
  LEASE: {
    RENEWAL_REQUESTED: 'lease.renewal.requested',
    RENEWAL_OFFERED: 'lease.renewal.offered',
    RENEWAL_APPROVED: 'lease.renewal.approved',
    RENEWAL_REJECTED: 'lease.renewal.rejected',
    RENEWAL_SIGNED: 'lease.renewal.signed',
    RENEWAL_COMPLETED: 'lease.renewal.completed',
    RENEWAL_CANCELLED: 'lease.renewal.cancelled'
  },
  PAYMENT: {
    COMPLETED: 'payment.completed',
    FAILED: 'payment.failed'
  },
  MAINTENANCE: {
    CREATED: 'maintenance.created',
    UPDATED: 'maintenance.updated'
  },
  USER: {
    LOGIN: 'user.login',
    LOGOUT: 'user.logout'
  },
  DOCUMENT: {
    UPLOADED: 'document.uploaded'
  },
  VERIFICATION: {
    SUBMITTED: 'verification.submitted',
    DOCUMENTS_UPLOADED: 'verification.documents.uploaded',
    AUTO_REVIEW_PASSED: 'verification.auto_review.passed',
    AUTO_REVIEW_FAILED: 'verification.auto_review.failed',
    APPROVED: 'verification.approved',
    REJECTED: 'verification.rejected',
    BADGE_ISSUED: 'verification.badge.issued',
    TRUST_UPDATED: 'verification.trust.updated',
    FLAG_RAISED: 'verification.flag.raised',
    EXPIRED: 'verification.expired',
    IDENTITY_STARTED: 'identity.verification.started',
    IDENTITY_DOC_UPLOADED: 'identity.document.uploaded',
    IDENTITY_PROCESSING: 'identity.verification.processing',
    IDENTITY_COMPLETED: 'identity.verification.completed',
    IDENTITY_VERIFIED: 'identity.verification.verified',
    IDENTITY_REVIEW_REQUIRED: 'identity.verification.review_required',
    IDENTITY_REJECTED: 'identity.verification.rejected',
    IDENTITY_FAILED: 'identity.verification.failed',
    PROPERTY_STARTED: 'property.verification.started',
    PROPERTY_DOC_UPLOADED: 'property.document.uploaded',
    PROPERTY_PROCESSING: 'property.document.processing',
    PROPERTY_COMPLETED: 'property.verification.completed',
    PROPERTY_VERIFIED: 'property.verification.verified',
    PROPERTY_REVIEW_REQUIRED: 'property.verification.review_required',
    PROPERTY_REJECTED: 'property.verification.rejected',
    PROPERTY_FAILED: 'property.verification.failed',
    PROPERTY_EXPIRED: 'property.verification.expired',
    PROPERTY_LOCKED: 'property.verification.locked',
    DIGILOCKER_STARTED: 'digilocker.connection.started',
    DIGILOCKER_COMPLETED: 'digilocker.connection.completed',
    DIGILOCKER_FAILED: 'digilocker.connection.failed',
    DIGILOCKER_DOC_LISTED: 'digilocker.document.listed',
    DIGILOCKER_DOC_IMPORTED: 'digilocker.document.imported',
    DIGILOCKER_DOC_FAILED: 'digilocker.document.failed',
    DIGILOCKER_REVOKED: 'digilocker.connection.revoked',
    FACIAL_CONSENT_GRANTED: 'facial.consent.granted',
    FACIAL_CONSENT_REVOKED: 'facial.consent.revoked',
    FACIAL_STARTED: 'facial.verification.started',
    FACIAL_PROCESSING: 'facial.verification.processing',
    FACIAL_VERIFIED: 'facial.verification.verified',
    FACIAL_REVIEW_REQUIRED: 'facial.verification.review_required',
    FACIAL_SPOOF_DETECTED: 'facial.verification.spoof_detected',
    FACIAL_REJECTED: 'facial.verification.rejected',
    FACIAL_FAILED: 'facial.verification.failed',
    FACIAL_LOCKED: 'facial.verification.locked',
    FACIAL_UNLOCKED: 'facial.verification.unlocked',
    FACIAL_METADATA_PURGED: 'facial.metadata.purged',
    VIDEO_KYC_CONSENT_GRANTED: 'video_kyc.consent.granted',
    VIDEO_KYC_CONSENT_REVOKED: 'video_kyc.consent.revoked',
    VIDEO_KYC_SESSION_CREATED: 'video_kyc.session.created',
    VIDEO_KYC_AGENT_ASSIGNED: 'video_kyc.agent.assigned',
    VIDEO_KYC_AGENT_JOINED: 'video_kyc.agent.joined',
    VIDEO_KYC_STARTED: 'video_kyc.verification.started',
    VIDEO_KYC_COMPLETED: 'video_kyc.verification.completed',
    VIDEO_KYC_VERIFIED: 'video_kyc.verification.verified',
    VIDEO_KYC_FLAGGED: 'video_kyc.verification.flagged',
    VIDEO_KYC_REJECTED: 'video_kyc.verification.rejected',
    VIDEO_KYC_FAILED: 'video_kyc.verification.failed',
    VIDEO_KYC_LOCKED: 'video_kyc.verification.locked',
    VIDEO_KYC_UNLOCKED: 'video_kyc.verification.unlocked',
    VIDEO_KYC_MEDIA_ACCESSED: 'video_kyc.media.accessed',
    VIDEO_KYC_METADATA_PURGED: 'video_kyc.metadata.purged',
    FRAUD_SCAN_STARTED: 'fraud.verification.scan_started',
    FRAUD_SIGNAL_DETECTED: 'fraud.verification.signal_detected',
    FRAUD_RISK_CALCULATED: 'fraud.verification.risk_calculated',
    FRAUD_REVIEW_REQUIRED: 'fraud.verification.review_required',
    FRAUD_CONFIRMED: 'fraud.verification.confirmed',
    FRAUD_DISMISSED: 'fraud.verification.dismissed',
    FRAUD_OVERRIDDEN: 'fraud.verification.overridden',
    FRAUD_UNAVAILABLE: 'fraud.verification.unavailable',
    FRAUD_LOCKED: 'fraud.verification.locked',
    FRAUD_UNLOCKED: 'fraud.verification.unlocked',
    FRAUD_CONFIG_CHANGED: 'fraud.config.changed',
    FRAUD_METADATA_PURGED: 'fraud.metadata.purged',
    SANCTION_SCAN_STARTED: 'sanction.verification.scan_started',
    SANCTION_MATCH_DETECTED: 'sanction.verification.match_detected',
    SANCTION_CONFIRMED: 'sanction.verification.confirmed',
    SANCTION_DISMISSED: 'sanction.verification.dismissed',
    SANCTION_UNAVAILABLE: 'sanction.verification.unavailable',
    SANCTION_UNLOCKED: 'sanction.verification.unlocked',
    SANCTION_METADATA_PURGED: 'sanction.metadata.purged',
  }
};
