/**
 * Metadata Section (A.1 / B.2 Page 1)
 * never split. Includes Version History when documentVersion > 1 (A.9, A.10)
 */

import PDFDocument from 'pdfkit';
import { DocumentModel, SectionDefinition } from '../types';
import { theme } from '../theme/tokens';
import { drawStatusChip } from '../components/StatusChip';

type Doc = InstanceType<typeof PDFDocument>;

export function renderMetadata(
  doc: Doc,
  model: DocumentModel,
  _def: SectionDefinition
): void {
  const { marginLeft, contentWidth } = theme.layout;

  // Section title
  doc
    .font('Helvetica-Bold')
    .fontSize(theme.typography.h1.size)
    .fillColor(theme.colors.navy900)
    .text('DOCUMENT METADATA');

  doc.moveDown(0.6);

  const cardY = doc.y;
  const rows = [
    ['Document ID', model.id.formatted, true],
    ['Generated By', model.generatedBy, false],
    ['Generated At', model.generatedAt, false],
    ['Lifecycle Status', model.lifecycle, false],
    ['Lease Version', model.data?.leaseVersion || model.version, false],
    [
      'Document Version',
      model.documentVersion > 1
        ? `v${model.documentVersion}  (see Version History)`
        : `v${model.documentVersion}`,
      false,
    ],
    ['Template Version', model.templateVersion, false],
  ] as [string, string, boolean][];

  const rowH = 16;
  const cardH = rows.length * rowH + 16;

  doc
    .roundedRect(marginLeft, cardY, contentWidth, cardH, theme.radii.card)
    .fill(theme.colors.white)
    .strokeColor(theme.colors.slate200)
    .lineWidth(0.8)
    .stroke();

  doc
    .roundedRect(marginLeft + 6, cardY + 6, contentWidth - 12, cardH - 12, theme.radii.card - 2)
    .fill(theme.colors.slate50)
    .strokeColor(theme.colors.slate200)
    .lineWidth(0.3)
    .stroke();

  let y = cardY + 12;
  rows.forEach(([label, value, mono]) => {
    doc
      .font('Helvetica')
      .fontSize(theme.typography.caption.size)
      .fillColor(theme.colors.slate500)
      .text(label, marginLeft + 14, y, { width: 140 });

    if (label === 'Lifecycle Status') {
      drawStatusChip(doc, value, marginLeft + 160, y - 2, { size: 'sm' });
    } else {
      doc
        .font(mono ? 'Courier' : 'Helvetica-Bold')
        .fontSize(mono ? theme.typography.mono.size : theme.typography.body.size)
        .fillColor(mono ? theme.colors.monoSlate : theme.colors.slate700)
        .text(value, marginLeft + 160, y, { width: contentWidth - 180 });
    }
    y += rowH;
  });

  doc.y = cardY + cardH + 12;

  // Version History table (A.9) — only if documentVersion > 1
  if (model.documentVersion > 1 && model.versionHistory?.length) {
    doc
      .font('Helvetica-Bold')
      .fontSize(theme.typography.h2.size)
      .fillColor(theme.colors.navy700)
      .text('Version History');

    doc.moveDown(0.4);

    const headers = ['Version', 'Created By', 'Created At', 'Reason', 'Changes'];
    const colWs = [50, 100, 90, 90, contentWidth - 330];
    let hx = marginLeft;

    doc.font('Helvetica-Bold').fontSize(7).fillColor(theme.colors.slate500);
    headers.forEach((h, i) => {
      doc.text(h, hx, doc.y, { width: colWs[i] });
      hx += colWs[i];
    });
    doc.moveDown(0.3);

    doc
      .strokeColor(theme.colors.slate200)
      .lineWidth(0.5)
      .moveTo(marginLeft, doc.y)
      .lineTo(marginLeft + contentWidth, doc.y)
      .stroke();
    doc.moveDown(0.3);

    model.versionHistory.forEach((entry) => {
      let xx = marginLeft;
      const vals = [
        entry.version,
        entry.createdBy,
        entry.createdAt,
        entry.reason,
        entry.changes,
      ];
      doc.font('Helvetica').fontSize(7).fillColor(theme.colors.slate700);
      vals.forEach((v, i) => {
        doc.text(v, xx, doc.y, { width: colWs[i] - 4 });
        xx += colWs[i];
      });
      doc.moveDown(0.6);
    });
  }
}
