import React from 'react';
import { X, Download, Printer, ShieldCheck, FileText } from 'lucide-react';

const formatCurrency = (val) => {
  if (val === undefined || val === null) return '₹0';
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(val);
};

export function LeaseDocumentPreviewModal({ isOpen, onClose, document, lease, property, tenant, activeRenewal }) {
  if (!isOpen) return null;

  const docName = document?.name || 'Current Lease Agreement.pdf';
  const rent = activeRenewal?.proposedRent || lease?.rentAmount || 0;
  const deposit = lease?.securityDeposit || 0;
  const propName = property?.name || 'Assigned Residence';
  const unitNumber = property?.unitNumber || '101';
  const tenantName = tenant?.name || 'Valued Tenant';

  const handlePrintDownload = () => {
    const printWin = window.open('', '_blank', 'width=850,height=900');
    if (!printWin) return;

    printWin.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${docName}</title>
          <style>
            body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #0f172a; line-height: 1.6; }
            .header { border-bottom: 2px solid #0284c7; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; }
            .title { font-size: 22px; font-weight: 800; color: #0284c7; }
            .subtitle { font-size: 12px; color: #64748b; }
            .section { background: #f8fafc; border: 1px solid #e2e8f0; padding: 20px; border-radius: 12px; margin-bottom: 20px; }
            .label { font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748b; }
            .val { font-size: 14px; font-weight: 700; color: #0f172a; margin-bottom: 10px; }
            .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }
            .footer { border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 11px; text-align: center; color: #94a3b8; }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <div class="title">TENANT LEASE AGREEMENT & RENEWAL RECORD</div>
              <div class="subtitle">Official Document Ref: ${document?.id || 'LSE-OFFICIAL'}</div>
            </div>
            <div>
              <div style="font-[900]; color: #059669;">VERIFIED DIGITAL DOCUMENT</div>
            </div>
          </div>

          <div class="section">
            <div class="grid">
              <div>
                <div class="label">Tenant Name</div>
                <div class="val">${tenantName}</div>
                <div class="label">Property & Unit</div>
                <div class="val">${propName} - Unit ${unitNumber}</div>
              </div>
              <div>
                <div class="label">Monthly Base Rent</div>
                <div class="val">${formatCurrency(rent)}</div>
                <div class="label">Security Deposit</div>
                <div class="val">${formatCurrency(deposit)}</div>
              </div>
            </div>
          </div>

          <div class="section">
            <div class="label">TERMS & CONDITIONS SPECIFICATION</div>
            <p style="font-size: 12px; color: #334155;">
              This agreement confirms the tenant lease obligations for ${propName}, Unit ${unitNumber}. Rent is due on the 1st of each month. All maintenance standards, quiet hours, and property guidelines remain binding under TMS platform regulations.
            </p>
          </div>

          <div class="footer">
            Printed on ${new Date().toLocaleString()} • Generated by Tenant Management System Enterprise Engine
          </div>
          <script>window.onload = function() { window.print(); }</script>
        </body>
      </html>
    `);
    printWin.document.close();
  };

  return (
    <div className="fixed inset-0 bg-slate-900/60 dark:bg-slate-950/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl w-full max-w-2xl p-6 shadow-2xl relative space-y-5 animate-scale-up max-h-[90vh] overflow-y-auto">
        <button
          onClick={onClose}
          className="absolute right-5 top-5 p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 rounded-xl transition cursor-pointer"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-600 dark:text-blue-400" />
            <div>
              <h2 className="text-base font-bold text-slate-900 dark:text-slate-100">{docName}</h2>
              <p className="text-[11px] text-slate-500">Document Version {document?.version || '1.0.0'}</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrintDownload}
              className="px-3.5 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs transition flex items-center gap-1.5 cursor-pointer shadow-sm"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download PDF</span>
            </button>
          </div>
        </div>

        {/* Document Viewer Frame simulation */}
        <div className="p-6 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-200/80 dark:border-slate-800 space-y-4 text-xs">
          <div className="flex items-center justify-between border-b border-slate-200/60 dark:border-slate-800/60 pb-3">
            <div>
              <span className="text-[10px] uppercase font-bold text-blue-600 dark:text-blue-400 tracking-wider">
                TENANT MANAGEMENT SYSTEM LEASE ARCHIVE
              </span>
              <h3 className="text-sm font-extrabold text-slate-900 dark:text-slate-100">{propName} (Unit {unitNumber})</h3>
            </div>
            <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-bold bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800">
              <ShieldCheck className="w-3 h-3" />
              DIGITALLY VERIFIED
            </span>
          </div>

          <div className="grid grid-cols-2 gap-3 font-mono text-[11px]">
            <div>
              <span className="text-slate-500 block">Lessee:</span>
              <strong className="text-slate-900 dark:text-slate-100">{tenantName}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">Monthly Rent:</span>
              <strong className="text-slate-900 dark:text-slate-100">{formatCurrency(rent)}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">Deposit:</span>
              <strong className="text-slate-900 dark:text-slate-100">{formatCurrency(deposit)}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">Lease Status:</span>
              <strong className="text-emerald-600 dark:text-emerald-400">ACTIVE / VERIFIED</strong>
            </div>
          </div>

          <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-[11px] leading-relaxed text-slate-600 dark:text-slate-400 space-y-2">
            <p>
              This document serves as the binding agreement governing unit residency, payment schedules, and maintenance protocols under local tenancy laws.
            </p>
            <p className="font-mono text-[10px] text-slate-400">
              SHA256 Checksum: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
            </p>
          </div>
        </div>

        <div className="flex justify-end pt-2">
          <button
            onClick={onClose}
            className="px-5 py-2.5 rounded-xl border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300 font-bold text-xs hover:bg-slate-100 transition cursor-pointer"
          >
            Close Preview
          </button>
        </div>
      </div>
    </div>
  );
}

export default LeaseDocumentPreviewModal;
