export const ROLE_PERMISSIONS = {
  admin: ['INITIATE', 'SUBMIT', 'RESUBMIT', 'UPLOAD', 'REVIEW_LEVEL2', 'APPROVE_LEVEL3', 'REJECT_LEVEL3', 'VIEW_ALL_QUEUE', 'VIEW_AUDIT_LOGS'],
  manager: ['INITIATE', 'SUBMIT', 'RESUBMIT', 'UPLOAD', 'REVIEW_LEVEL2', 'VIEW_MANAGED_PROPERTIES'],
  tenant: ['INITIATE_SELF', 'SUBMIT_SELF', 'RESUBMIT_SELF', 'UPLOAD_SELF', 'VIEW_SELF_HISTORY'],
  technician: ['INITIATE_SELF', 'SUBMIT_SELF', 'RESUBMIT_SELF', 'UPLOAD_SELF', 'VIEW_SELF_HISTORY'],
};
