export const ENTITY_TYPES = {
  TENANT: 'TENANT',
  MANAGER: 'MANAGER',
  PROPERTY: 'PROPERTY',
  TECHNICIAN: 'TECHNICIAN',
  VENDOR: 'VENDOR',
  BROKER: 'BROKER',
};

export const VERIFICATION_STATUS_TYPES = {
  DRAFT: 'DRAFT',
  DOCUMENTS_UPLOADED: 'DOCUMENTS_UPLOADED',
  SUBMITTED: 'SUBMITTED',
  AUTO_REVIEW: 'AUTO_REVIEW',
  MANAGER_REVIEW: 'MANAGER_REVIEW',
  ADMIN_REVIEW: 'ADMIN_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
};

export const BADGE_TIERS = {
  UNVERIFIED: 'UNVERIFIED',
  BRONZE: 'BRONZE',
  SILVER: 'SILVER',
  GOLD: 'GOLD',
  PLATINUM: 'PLATINUM',
};

export const REVIEW_LEVELS = {
  LEVEL_1_AUTO: 'LEVEL_1_AUTO',
  LEVEL_2_MANAGER: 'LEVEL_2_MANAGER',
  LEVEL_3_ADMIN: 'LEVEL_3_ADMIN',
};

export const RISK_LEVELS_ENUM = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};
